{
    'alpha': 100000000,
    'u_layers': 8,
    'u_hidden_dim': 20,
    'u_hidden_hidden_dim': 10,
    'v_layers': 9,
    'v_hidden_dim': 50,
    'n1': 2,
    'n2': 1,
    'u_rate': 0.015,
    'v_rate': 0.04,
    'min_steps': 5,
    'adjoint': False,
    'solver': 'midpoint',
    'dim': 5,
    'N_t': 20,
    'N_r': 4000,
    'N_b': 4000,
    'T0': 0,
    'T': 1,
    'shape_param': [-1, 1],
    'iterations': 201,
    'domain': Hypercube
}